com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
	at com.intellij.database.serialization.FixHierarchicalStreamReader.hasMoreChildren(FixHierarchicalStream.kt)
	at com.intellij.database.serialization.ModelImporter.deserializeModel(ModelImporter.java:90)
	at com.intellij.database.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:37)
	at com.intellij.database.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:27)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:683)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:671)
	at com.intellij.database.dataSource.DataSourceStorage.loadModels(DataSourceStorage.java:488)
	at com.intellij.database.dataSource.DataSourceStorage.access$000(DataSourceStorage.java:90)
	at com.intellij.database.dataSource.DataSourceStorage$2.run(DataSourceStorage.java:398)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xmlpull.v1.XmlPullParserException: unexpected character in markup < (position: END_TAG seen ...</collation>\n<<... @962:3) 
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1261)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 25 more
